### ISSUE TITLE
Difference between MixtureBSDF and PhongBSDF?

### ISSUE THREAD

**Issue by GabrielAlacchi** [ecsex46/fall-2019#4]
Hi I'm getting a head start on A5 so I don't get swamped with projects and midterms starting soon. I noticed this file has TODOs but isn't mentioned anywhere on the handout and appears to be a mixture model between phong and diffuse. Didn't we already implement this previously in the PhongBSDF file? 

https://github.com/ecsex46/fall-2019/blob/master/src/bsdfs/mixture.h

My scenes for A5 don't render correctly as some of the objects have this BSDF associated to it. Not sure whether we're meant to add code to this file or if it was a mistake.

**Comment by joeylitalien** [comment]
Good catch! In 2018, the mixture was actually the Phong mixture model you implemented in A3. We had students implement pure Phong in A3 and then add the diffuse term for the mixture model in A5. This ordering was rather illogical so we simply merged the two BSDFs for the 2019 version of the course.

You can completely ignore `bsdfs/mixture.h` but we will have to update the scene material files to reflect this change. This will be done before the A4 deadline: changing `illum 8` to `illum 7` in all `.mtl` files should allow you to render the scenes in the meantime.

**Comment by joeylitalien** [comment]
Fixed in [latest commit](https://github.com/ecsex46/fall-2019/commit/bd7a64f56b5e16a0ec7ec9863363d8951b43b188).
